rag-model:
  - name: Qwen/Qwen2.5-7B-Instruct-AWQ
    type: qwen

input:
  - model: Qwen/Qwen2.5-7B-Instruct-AWQ
    quantization: awq_marlin
    gpu_memory_utilization: 0.85
    max_model_len: 8192
    trust_remote_code: True
